default:
  image: node:18.12.0

variables:
  IMAGE_NAME: registry.gitlab.com/ultra-x/ultrax-web-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
#  IMAGE_NAME: registry.gitlab.u2sec.io/u2u-ultrax/docker-image/web-app
#  IMAGE_TAG: main

stages:
  - build
#  - deploy

#deploy_preview:
#  stage: deploy
#  only:
#    - main
#  script:
#    - npm install --global vercel
#    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
#    - vercel build --token=$VERCEL_TOKEN
#    - vercel deploy --prebuilt --token=$VERCEL_TOKEN
#
#deploy_production:
#  stage: deploy
#  only:
#    - tags
#  script:
#    - npm install --global vercel
#    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
#    - vercel build --prod --token=$VERCEL_TOKEN
#    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

docker build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  only:
    refs:
      - main
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

#deploy to development:
#  stage: deploy
#  image: registry.digitalocean.com/ultra-x/k8s-deployer:latest
#  only:
#    - main
#  variables:
#    HOST: utx.bestsoft.dev
#    NAMESPACE: development
#  script: cd k8s && bash deploy.sh
